name: build-documentation
on: [push]
jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - uses: docker://pandoc/latex:2.13
        with:
          args: "--output=output/user-guide.pdf -H head.tex -f gfm --shift-heading-level-by -1 user-guide.md"
      - uses: docker://pandoc/latex:2.13
        with:
          args: "--output=output/construction-guide.pdf -H head.tex -f gfm --shift-heading-level-by -1 construction-guide.md"
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
